name = "food-generator"
compatibility_date = "2025-02-13"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "food-generator-db"
database_id = "d636b58f-6450-498c-8c21-75badbf32258"
migrations_dir = "./migrations"

[vars]
GITHUB_OWNER = "artteabcn"
TEMPLATE_REPO = "restaurant-template"

